from calendar import Calendar, PeriodicExpression

c_basic = Calendar('basic', 0, None, [1])
c_minutes = Calendar('minutes', 0, c_basic, [1])
c_hours = Calendar('hours', 0, c_minutes, [60])
c_days = Calendar('days', 0, c_hours, [24])
c_weeks = Calendar('weeks', 0, c_days, [7])
print(c_basic[10])
print(c_minutes[12])
print(c_hours[0])
print(c_hours[1])
print(c_days[0])
print(c_days[1])

pe1 = PeriodicExpression("pe1", [[0],[0,2,3],[0,2,6],[0,30]], [c_weeks, c_days, c_hours, c_minutes], 1, c_minutes)
pe2 = PeriodicExpression("business_hours", [["all"],[0,1,2,3,4],[8],[30]], [c_weeks, c_days, c_hours, c_minutes], 510, c_minutes)
print(pe1[0])
print(pe1[1])
print(pe1[2])
print(pe1[3])
print(pe1[4])
print(pe1[5])
print(pe1[6])
print(pe1[7])
print(pe1[8])
print(pe2[7])
#print(pe1.calculate_(10))
